# Generated by Django 4.2.26 on 2025-11-14 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='脚本名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='脚本描述')),
                ('content', models.JSONField(verbose_name='脚本内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', '待处理'), ('RUNNING', '运行中'), ('SUCCESS', '成功'), ('FAILED', '失败'), ('PAUSED', '已暂停')], default='PENDING', max_length=10, verbose_name='任务状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('latest_screenshot', models.CharField(blank=True, max_length=255, null=True, verbose_name='最新截图')),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.script', verbose_name='关联脚本')),
            ],
        ),
    ]
