# Generated by Django 4.2.26 on 2025-11-15 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='log',
            field=models.TextField(blank=True, null=True, verbose_name='任务日志'),
        ),
    ]
