# Generated by Django 4.2.26 on 2025-11-16 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_task_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='device_uri',
            field=models.CharField(blank=True, help_text='执行此任务时使用的设备URI', max_length=255, null=True, verbose_name='设备URI'),
        ),
    ]
