# Generated by Django 4.2.26 on 2025-11-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_task_device_uri'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='celery_task_id',
            field=models.CharField(blank=True, help_text='Celery后台任务的唯一ID', max_length=255, null=True, verbose_name='Celery任务ID'),
        ),
    ]
