# Generated by Django 4.2.26 on 2025-11-19 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_task_celery_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scripts', to=settings.AUTH_USER_MODEL, verbose_name='所有者'),
        ),
        migrations.AddField(
            model_name='task',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='所有者'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('PENDING', '待处理'), ('RUNNING', '运行中'), ('SUCCESS', '成功'), ('FAILED', '失败'), ('PAUSED', '已暂停'), ('CANCELED', '已取消')], default='PENDING', max_length=10, verbose_name='任务状态'),
        ),
    ]
